services:
  jupyterlab:
    container_name: jupyterlab
    image: v8040/jupyterlab:latest
    ports:
      - '8888:8888'
    environment:
      - TZ=Asia/Shanghai
      - NOTEBOOK_ARGS="--ServerApp.token=''"
    volumes:
      - ./work:/home/jovyan/work
      - ./envs:/opt/conda/envs
    command: start-notebook.py --ServerApp.root_dir=/home/jovyan/work